[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
composeBom = "2024.09.00"
ktor = "3.4.0"
foundationLayout = "1.10.2"

kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.7.1"

koin = "4.1.1"

coil = "2.7.0"
compose-animation = "1.10.2"
compose-runtime = "1.10.2"

pagingRuntimeKtx = "3.4.0"
firebaseCrashlyticsBuildtools = "3.0.6"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }


ktor-client-core = {module = "io.ktor:ktor-client-core", version.ref = "ktor"}
ktor-client-content-negotiation = {module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor"}
ktor-serialization-json = {module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor"}
ktor-client-okhttp = {module = "io.ktor:ktor-client-okhttp", version.ref = "ktor"}
ktor-client-logging = {module = "io.ktor:ktor-client-logging", version.ref = "ktor"}
kotlinx-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization-json", version.ref = "kotlinx-serialization"}



kotlinx-coroutines-core = { module = "org.jetbrains.kotlin:kotlin-coroutines-core", version.ref = "kotlinx-coroutines"}
kotlinx-datetime = { module = "org.jetbrains.kotlin:kotlin-datetime", version.ref = "kotlinx-datetime"}


androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundationLayout"}


androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose-animation"}
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime"}
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil"}

# Paging3

androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingRuntimeKtx" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "pagingRuntimeKtx" }

koin-core = { module = "io.insert-koin:koin-core", version.ref ="koin"}
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref ="koin"}
koin-compose = { module = "io.insert-koin:koin-compose", version.ref ="koin"}
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }


[bundles]
ktor = ["ktor-client-core", "ktor-serialization-json", "ktor-client-okhttp", "ktor-client-content-negotiation", "ktor-client-logging", "kotlinx-serialization" ]
koin = ["koin-core", "koin-compose", "koin-androidx-compose"]
kotlin-coroutines = ["kotlinx-coroutines-core", "kotlinx-datetime", "kotlinx-serialization"]
paging3 = ["androidx-paging-compose", "androidx-paging-runtime-ktx", "androidx-paging-common"]



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp"}
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

